### ISSUE TITLE
Getting album art into /tmp/shairport-sync/

### ISSUE THREAD

**Issue by NickSutton** [effektsvk/shairport-sync-metadata-webserver#1]
Hi,

I like your work, cool idea and good presentation.

I think I’m missing a trick though!  How did you get the album art from the pipe to the /tmp/shairport-sync folder as required in your first IF statement?

Also, where has /root/shairport-sync-metadata-webserver come from, is this something else to install?

I’ve got the pipe working fine, I can read album name, artist and track using another script but this one keeps printing ‘music not playing’... Could I have some pointers please?

Thanks for your hard work

**Comment by effektsvk** [comment]
Hello!

The album art gets exported by pipe as well. Your ```shairport-sync.conf``` (usually here: ```/etc/shairport-sync.conf/```) should contain this:
```
// How to deal with metadata, including artwork
metadata =
{
      enabled = "yes"; // enables the pipe
      include_cover_art = "yes"; // includes album art, this is what you need
      pipe_name = "/tmp/shairport-sync"; // this is the pipe address, make sure to set it to /tmp/shairport-sync so it is the same as in copyscript.py
};
```

```/root/shairport-sync-metadata-webserver``` is this folder of this repo, where all of your files are. I'm sorry, I am aware the documentation is terrible 😄 Basically I uploaded it just so I can easily git clone it to my NAS but thanks for using it! ❤️

**Comment by effektsvk** [comment]
I'm closing the issue, if you need something else, I will gladly reopen it. 😉

**Comment by NickSutton** [comment]
Erik,

I changed your code to make use of their things I had learnt and now have a working solution!
I will share my code here when I’ve put my Pi back together! 
Your .js script really helped me out.

Thanks,
Nick

**Comment by effektsvk** [comment]
I'm very glad that I helped. Enjoy!
